"""Generate the mod's embedded inspection-description lookup from the review catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SIGN_IDS = {"EYE": 0, "HANDS": 1, "TEETH": 2, "AURAPHOTO": 3, "ARMPIT": 4, "EAR": 5}


def normalize_sprite(name: str) -> str:
    return name.strip().casefold()


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n") + '"'


def generate(catalog_path: Path, output_path: Path) -> tuple[int, int]:
    records = json.loads(catalog_path.read_text(encoding="utf-8"))
    entries: dict[str, str] = {}
    excluded = 0

    for record in records:
        sign_name = str(record.get("sign", "")).upper()
        sign = SIGN_IDS.get(sign_name)
        side = str(record.get("side", "")).lower()
        verbose_description = str(record.get("description", "")).strip()
        sprites = [normalize_sprite(str(sprite)) for sprite in record.get("sprites", [])]
        if (
            sign is None
            or side not in {"human", "imposter", "other"}
            or not verbose_description
            or not sprites
            or record.get("status") == "rejected"
            or record.get("validation_issues")
        ):
            excluded += 1
            continue

        # side="other" means the sprite is shown regardless of the character's true nature (e.g. armpit_6, the only
        # armpit Firefighter/Intruder have). The runtime always reads the human OR imposter field per _isImposter, never
        # an "other" side, so emit such records under BOTH sides so the lookup matches whichever the runtime computes.
        sides = ["human", "imposter"] if side == "other" else [side]

        description = verbose_description

        # The catalog key MUST match the signature the mod computes at runtime (SignNarrator), or the lookup misses and
        # the sign falls back to a bare neutral prompt. For EYE, the runtime reads exactly one _white + one _iris sprite
        # off CharacterEyeData and keys on "white|iris" — but the source rows list extra trailing eye sprites (multiple
        # white variants), so keying on the full list left ~20 eye entries (3-4 sprites) permanently unmatchable. The
        # real white/iris pair is always the FIRST TWO sprites, so truncate EYE keys to those two. (Armpit/ear are
        # already reduced to their final frame upstream in pipeline.py; this mirrors that for eyes.)
        key_sprites = sprites[:2] if sign == SIGN_IDS["EYE"] else sprites
        for emit_side in sides:
            key = f"{sign}|{1 if emit_side == 'imposter' else 0}|{'|'.join(key_sprites)}"
            previous = entries.get(key)
            if previous is not None and previous != description:
                # Two source images collapse to the same white|iris pair (trailing sprites the runtime can't see
                # differed). The runtime can't tell them apart either, so keep the FIRST and skip rather than crash.
                print(f"  note: key {key} collapses to two descriptions; keeping first, skipping duplicate.")
                continue
            entries[key] = description

    lines = [
        "// Generated by tools/visitor-image-describer/generate_csharp_catalog.py.",
        "// Candidate entries with validation issues and records marked rejected are excluded.",
        "#nullable enable",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace NoImNotAHumanAccess.World",
        "{",
        "    internal static class SignDescriptionCatalog",
        "    {",
        "        private static readonly Dictionary<string, string> Entries = new(StringComparer.Ordinal)",
        "        {",
    ]
    for key, description in sorted(entries.items()):
        lines.append(f"            [{csharp_string(key)}] = {csharp_string(description)},")
    lines.extend(
        [
            "        };",
            "",
            "        internal static bool TryGet(int sign, bool isImposter, string? spriteSignature, out string description)",
            "        {",
            "            description = string.Empty;",
            "            if (string.IsNullOrWhiteSpace(spriteSignature)) return false;",
            "            string[] sprites = spriteSignature!.Split('|');",
            "            for (int i = 0; i < sprites.Length; i++)",
            "                sprites[i] = sprites[i].Trim().ToLowerInvariant();",
            "            string key = $\"{sign}|{(isImposter ? 1 : 0)}|{string.Join(\"|\", sprites)}\";",
            "            return Entries.TryGetValue(key, out description!);",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return len(entries), excluded


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("catalog", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    included, excluded = generate(args.catalog, args.output)
    print(f"Generated {included} entries; excluded {excluded} records")


if __name__ == "__main__":
    main()
