"""Generate the mod's embedded inspection-description lookup from the review catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SIGN_IDS = {"EYE": 0, "HANDS": 1, "TEETH": 2, "AURAPHOTO": 3, "ARMPIT": 4, "EAR": 5}


def normalize_sprite(name: str) -> str:
    return name.strip().casefold()


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n") + '"'


def generate(catalog_path: Path, output_path: Path) -> tuple[int, int]:
    records = json.loads(catalog_path.read_text(encoding="utf-8"))
    entries: dict[str, str] = {}
    excluded = 0

    for record in records:
        sign_name = str(record.get("sign", "")).upper()
        sign = SIGN_IDS.get(sign_name)
        side = str(record.get("side", "")).lower()
        verbose_description = str(record.get("description", "")).strip()
        sprites = [normalize_sprite(str(sprite)) for sprite in record.get("sprites", [])]
        if (
            sign is None
            or side not in {"human", "imposter"}
            or not verbose_description
            or not sprites
            or record.get("status") == "rejected"
            or record.get("validation_issues")
        ):
            excluded += 1
            continue

        description = verbose_description
        key = f"{sign}|{1 if side == 'imposter' else 0}|{'|'.join(sprites)}"
        previous = entries.get(key)
        if previous is not None and previous != description:
            raise ValueError(f"Conflicting descriptions for {key}")
        entries[key] = description

    lines = [
        "// Generated by tools/visitor-image-describer/generate_csharp_catalog.py.",
        "// Candidate entries with validation issues and records marked rejected are excluded.",
        "#nullable enable",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace NoImNotAHumanAccess.World",
        "{",
        "    internal static class SignDescriptionCatalog",
        "    {",
        "        private static readonly Dictionary<string, string> Entries = new(StringComparer.Ordinal)",
        "        {",
    ]
    for key, description in sorted(entries.items()):
        lines.append(f"            [{csharp_string(key)}] = {csharp_string(description)},")
    lines.extend(
        [
            "        };",
            "",
            "        internal static bool TryGet(int sign, bool isImposter, string? spriteSignature, out string description)",
            "        {",
            "            description = string.Empty;",
            "            if (string.IsNullOrWhiteSpace(spriteSignature)) return false;",
            "            string[] sprites = spriteSignature!.Split('|');",
            "            for (int i = 0; i < sprites.Length; i++)",
            "                sprites[i] = sprites[i].Trim().ToLowerInvariant();",
            "            string key = $\"{sign}|{(isImposter ? 1 : 0)}|{string.Join(\"|\", sprites)}\";",
            "            return Entries.TryGetValue(key, out description!);",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return len(entries), excluded


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("catalog", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    included, excluded = generate(args.catalog, args.output)
    print(f"Generated {included} entries; excluded {excluded} records")


if __name__ == "__main__":
    main()
